[tool.poetry]
name = "riteh-discord-bot"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"
"discord.py" = "^2.4.0"
beautifulsoup4 = "^4.12.3"
cachetools = "^5.5.0"
fuzzywuzzy = "^0.18.0"
